---
extends: semistandard
globals:
  artifacts: readonly
rules:
  comma-dangle:
    - error
    - always-multiline
  object-curly-spacing:
    - error
    - never
  linebreak-style:
    - error
    - unix
  operator-linebreak: off
  promise/param-names:
    - off
  space-before-function-paren:
    - error
    - anonymous: never
      named: never
      asyncArrow: always
env:
  browser: true
